### ISSUE TITLE
override.settings.yaml is invalid if generated by InstallTool

### ISSUE THREAD

**Issue by schloram** [helhum/typo3-config-handling#36]
Hi Helmut,
I hope you are doing well.

First: I have to admit I have no idea if this issue is better off in `helhum/config-loader` or here. But as this is the package I'm requiring directly I opened it here.

I have a weird behavior with the current version (v1.0.5) and need some guidance. :)

Background:
We are using ddev for development and have all default settings set up in `settings.yaml` (with env variables where necessary).
Since the [AdditionalConfiguration created by ddev](https://github.com/drud/ddev/blob/master/pkg/ddevapp/typo3/AdditionalConfiguration.php) itself is useless with the `typo3-config-handling` we have this configuration inside a `ddev.yaml` which is included inside the `dev.settings.yaml`.

So actually when a developer starts to develop on a project for the first time there is no need for the `override.settings.yaml` to be existent because everything is set up either in the `settings.yaml` and/or the `dev.settings.yaml` (and includes) already.

But as soon one tries to open the InstallTool when there is no `override.settings.yaml` present the InstallTool initialization got stuck on the "Checking session and executing silent configuration update" loop.

The main problem here is that on the first try of the `executeSilentConfigurationUpdate` process an invalid yaml is generated. Then all following executions fail completely due to invalid yaml.

Invalid `override.settings.yaml` that is being created when opening the InstallTool:
```
processors:
    - { class: Helhum\TYPO3\ConfigHandling\Processor\RemoveSettingsProcessor, paths: ['"SYS"."sqlDebug"', '"SYS"."enableDeprecationLog"'], internal: true }

{  }
```

Error after the first `executeSilentConfigurationUpdate` execution:
```
Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 4 (near "{ }"). in /var/www/html/vendor/symfony/yaml/Parser.php:380 Stack trace: #0 /var/www/html/vendor/symfony/yaml/Parser.php(97): Symfony\Component\Yaml\Parser->doParse(Array, 0) #1 /var/www/html/vendor/symfony/yaml/Yaml.php(80): Symfony\Component\Yaml\Parser->parse('processors:\n ...', 0) #2 /var/www/html/vendor/helhum/config-loader/src/Reader/YamlFileReader.php(41): Symfony\Component\Yaml\Yaml::parse('processors:\n ...') #3 /var/www/html/vendor/helhum/config-loader/src/Reader/RootConfigFileReader.php(50): Helhum\ConfigLoader\Reader\YamlFileReader->readConfig() #4 /var/www/html/vendor/helhum/config-loader/src/ConfigurationLoader.php(53): Helhum\ConfigLoader\Reader\RootConfigFileReader->readConfig() #5 /var/www/html/vendor/helhum/config-loader/src/Reader/CollectionReader.php(40): Helhum\ConfigLoader\ConfigurationLoader->load() #6 /var/www/html/vendor/helhum/typo3-config-handling/src/ConfigReader/CustomProcessingReader.php(47): Helhum\ConfigLoader\Reader\CollectionReader->readConfig() #7 /var/www/html/vendor/helhum/typo3-config-handling/src/Typo3Config.php(103): Helhum\TYPO3\ConfigHandling\ConfigReader\CustomProcessingReader->readConfig() #8 /var/www/html/vendor/helhum/config-loader/src/ConfigurationLoader.php(53): Helhum\TYPO3\ConfigHandling\Typo3Config->readConfig() #9 /var/www/html/vendor/helhum/typo3-config-handling/src/ConfigLoader.php(100): Helhum\ConfigLoader\ConfigurationLoader->load() #10 /var/www/html/vendor/helhum/typo3-config-handling/src/ConfigLoader.php(60): Helhum\TYPO3\ConfigHandling\ConfigLoader->load() #11 /var/www/html/vendor/helhum/typo3-config-handling/src/Xclass/ConfigurationManager.php(475): Helhum\TYPO3\ConfigHandling\ConfigLoader->populate() #12 /var/www/html/public/typo3/sysext/core/Classes/Core/Bootstrap.php(315): Helhum\TYPO3\ConfigHandling\Xclass\ConfigurationManager->exportConfiguration() #13 /var/www/html/public/typo3/sysext/core/Classes/Core/Bootstrap.php(96): TYPO3\CMS\Core\Core\Bootstrap::populateLocalConfiguration(Object(Helhum\TYPO3\ConfigHandling\Xclass\ConfigurationManager)) #14 /var/www/html/public/typo3/index.php(20): TYPO3\CMS\Core\Core\Bootstrap::init(Object(Composer\Autoload\ClassLoader)) #15 /var/www/html/public/typo3/index.php(21): {closure}() #16 {main} Next Helhum\ConfigLoader\InvalidConfigurationFileException: Error while parsing file "/var/www/html/config/override.settings.yaml", Message: "Unable to parse at line 4 (near "{ }")." in /var/www/html/vendor/helhum/config-loader/src/Reader/YamlFileReader.php:43 Stack trace: #0 /var/www/html/vendor/helhum/config-loader/src/Reader/RootConfigFileReader.php(50): Helhum\ConfigLoader\Reader\YamlFileReader->readConfig() #1 /var/www/html/vendor/helhum/config-loader/src/ConfigurationLoader.php(53): Helhum\ConfigLoader\Reader\RootConfigFileReader->readConfig() #2 /var/www/html/vendor/helhum/config-loader/src/Reader/CollectionReader.php(40): Helhum\ConfigLoader\ConfigurationLoader->load() #3 /var/www/html/vendor/helhum/typo3-config-handling/src/ConfigReader/CustomProcessingReader.php(47): Helhum\ConfigLoader\Reader\CollectionReader->readConfig() #4 /var/www/html/vendor/helhum/typo3-config-handling/src/Typo3Config.php(103): Helhum\TYPO3\ConfigHandling\ConfigReader\CustomProcessingReader->readConfig() #5 /var/www/html/vendor/helhum/config-loader/src/ConfigurationLoader.php(53): Helhum\TYPO3\ConfigHandling\Typo3Config->readConfig() #6 /var/www/html/vendor/helhum/typo3-config-handling/src/ConfigLoader.php(100): Helhum\ConfigLoader\ConfigurationLoader->load() #7 /var/www/html/vendor/helhum/typo3-config-handling/src/ConfigLoader.php(60): Helhum\TYPO3\ConfigHandling\ConfigLoader->load() #8 /var/www/html/vendor/helhum/typo3-config-handling/src/Xclass/ConfigurationManager.php(475): Helhum\TYPO3\ConfigHandling\ConfigLoader->populate() #9 /var/www/html/public/typo3/sysext/core/Classes/Core/Bootstrap.php(315): Helhum\TYPO3\ConfigHandling\Xclass\ConfigurationManager->exportConfiguration() #10 /var/www/html/public/typo3/sysext/core/Classes/Core/Bootstrap.php(96): TYPO3\CMS\Core\Core\Bootstrap::populateLocalConfiguration(Object(Helhum\TYPO3\ConfigHandling\Xclass\ConfigurationManager)) #11 /var/www/html/public/typo3/index.php(20): TYPO3\CMS\Core\Core\Bootstrap::init(Object(Composer\Autoload\ClassLoader)) #12 /var/www/html/public/typo3/index.php(21): {closure}() #13 {main} thrown in /var/www/html/vendor/helhum/config-loader/src/Reader/YamlFileReader.php on line 43
```

- TYPO3: 11.5.4
- PHP: 8.0
- helhum/typo3-config-handling: 1.0.5

**Comment by helhum** [comment]
@schloram I agree that there is some things that can be fixed here in this package. In the meantime, I suggest to keep your overall configuration clean and not use removed values like `SYS.sqlDebug` and `SYS. enableDeprecationLog` if you look for that in your config folder and remove all occurrences, then the install tool will not create an override.settings.yaml at all.

**Comment by schloram** [comment]
@helhum Well, that was easy. :D I somehow missed that these values were still in my config. Thanks a ton! Do you want me to leave this issue open for keeping track of this misbehavior and a future improvement?

**Comment by schloram** [comment]
Hi @helhum ,

while playing around with this extension again for our own internal TYPO3 Project Templates I figured out where the bug is located at.
Not sure if PR https://github.com/helhum/typo3-config-handling/pull/53 meets your requirements but it solves the problem. :)

Let me know what you think.
